/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_Main */

#ifndef _Included_com_company_Main
#define _Included_com_company_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_Main
 * Method:    splineFitting
 * Signature: ([D[DID)D
 */
JNIEXPORT jdouble JNICALL Java_com_company_Main_splineFitting
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
